{
 "title": "Details",
 "description": "This dashboard to present Jmeter result",
 "time": { "from": "2023-06-05T07:09:09.340Z", "to": "2023-06-06T07:09:09.340Z" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "Scenario",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.bucket,\r\n  tag: \"scenario\",\r\n  predicate: (r) => r._measurement == \"requestsRaw\",\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "userLocation",
    "label": "User Location",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.bucket,\r\n  tag: \"userLocation\",\r\n  predicate: (r) => r._measurement == \"requestsRaw\" and r.scenario =~ /${scenario:regex}/,\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "connectionType",
    "label": "Connection Type",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.bucket,\r\n  tag: \"connectionType\",\r\n  predicate: (r) => r._measurement == \"requestsRaw\" and r.scenario =~ /${scenario:regex}/,\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "btpLocation",
    "label": "BTP Location",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.bucket,\r\n  tag: \"btpLocation\",\r\n  predicate: (r) => r._measurement == \"requestsRaw\" and r.scenario =~ /${scenario:regex}/,\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "s4hLocation",
    "label": "S4H Location",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.bucket,\r\n  tag: \"s4hLocation\",\r\n  predicate: (r) => r._measurement == \"requestsRaw\",\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "request",
    "label": "Request",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.bucket,\r\n  tag: \"requestName\",\r\n  predicate: (r) => r._measurement == \"requestsRaw\",\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)"
   },
   {
    "name": "aggregation",
    "label": "Aggregation",
    "query": "Average : 0.0, Median : 0.50, 90th Percentile : 0.90, 95th Percentile : 0.95, 99th Percentile : 0.99, "
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Regional Metrics (${aggregation})",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)  \r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\", \"btpLocation\",\"s4hLocation\"]) \r\n  |> count()\r\n  |> group()\r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)  \r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregate()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"RT (Avg)\"})\r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"RT (Avg)\"])  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)  \r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregate()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"RT (pctl)\"})  \r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"RT (pctl)\"])  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)  \r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> toFloat()\r\n  |> stddev()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"RT (Deviation)\"})  \r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"RT (Deviation)\"])  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> max()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"RT (Max)\"})  \r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"btpLocation\",\"connectionType\",\"s4hLocation\",\"RT (Max)\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)   \r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\", \"btpLocation\",\"s4hLocation\"])\r\n  |> aggregate()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Latency\"})\r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"Latency\"])"
    },
    {
     "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"connectTime\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)  \r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregate()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Connect Time\"})  \r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"Connect Time\"])"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "failuresPercentages = () => {\r\n\r\ncountResponseTime=from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/) \r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> count()\r\n  |> group()\r\n  |> toFloat()\r\n  |> keep(columns: [\"_value\", \"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n\r\n  \r\nsumerrorCount=from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"errorCount\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)  \r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> sum()\r\n  |> group()\r\n  |> toFloat()\r\n  |> keep(columns: [\"_value\", \"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n\r\n  return join(\r\n      tables:{countResponseTime:countResponseTime, sumerrorCount:sumerrorCount},\r\n      on:[\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"]\r\n    )\r\n    |> map(fn:(r) => ({\r\n             \"scenario\":r.scenario,\r\n             \"userLocation\": r.userLocation,\r\n             \"connectionType\": r.connectionType,\r\n             \"btpLocation\": r.btpLocation,\r\n             \"s4hLocation\": r.s4hLocation,\r\n             \"Error Rate\": r._value_sumerrorCount / r._value_countResponseTime         \r\n    }))       \r\n}\r\nfailuresPercentages()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics-scc-total\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregate()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"SCC Time\"})\r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"SCC Time\"])"
    },
    {
     "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics-total\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregate()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"S4H Time\"})\r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"S4H Time\"])\r\n"
    },
    {
     "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics-icmtotal\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregate()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"ICM Time\"})\r\n  |> keep(columns: [\"scenario\", \"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\",\"ICM Time\"])"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Times (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  ",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "ICM Time (${aggregation}) ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics-icmtotal\")\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  ",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "S4H Time (${aggregation}) ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics-total\")\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\n  |> filter(fn: (r) => r[\"requestName\"] =~ /${request:regex}/)\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  ",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "SCC Time (${aggregation}) ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics-scc-total\")\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\n  |> filter(fn: (r) => r[\"requestName\"] =~ /${request:regex}/)\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\n  |> group(columns: [\"scenario\",\"userLocation\",\"btpLocation\",\"s4hLocation\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  ",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\")  \r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  \r\n",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connection Time (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"connectTime\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  \r\n",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Processing Time = Latency - Connect Time (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processingTime\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false) ",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Threads Over Time (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Sent Bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean()\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"allThreads\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false) ",
       "select": [
        [
         { "params": [ "receivedBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "!=", "value": "select tag value" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Failed Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Request Response Time (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Sent Bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean()\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\r\n  |> filter(fn: (r) => r[\"result\"] == \"fail\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  ",
       "select": [
        [
         { "params": [ "receivedBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "!=", "value": "select tag value" }
       ]
      }
     ]
    },
    {
     "title": "Pass Request Response Time (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Sent Bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean()\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\r\n  |> filter(fn: (r) => r[\"result\"] == \"pass\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"requestName\"] =~ /${request:regex}/)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  ",
       "select": [
        [
         { "params": [ "receivedBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "!=", "value": "select tag value" }
       ]
      }
     ]
    },
    {
     "title": "Failed Request Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Sent Bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"errorCount\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 1)\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => if exists (r[\"requestName\"]) then r[\"requestName\"]=~ /${request:regex}$/ else true)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)  ",
       "select": [
        [
         { "params": [ "receivedBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "!=", "value": "select tag value" }
       ]
      }
     ]
    },
    {
     "title": "Error Summary",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"errorCount\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 1)\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> group(columns: [\"requestName\", \"responseCode\", \"errorMessage\", \"errorResponseBody\"])\r\n  |> sum()\r\n  |> group()\r\n  |> keep(columns: [\"requestName\", \"errorMessage\", \"errorResponseBody\", \"responseCode\", \"_value\"])\r\n  |> rename(columns: {\"_value\": \"Count\"})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "S4H Ping Time (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ping-s4h\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"requestName\"] =~ /${request:regex}/)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  \r\n",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SCC Ping Time (${aggregation})",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "aggregate = if  ${aggregation} > 0 then (tables=<-) => tables |>  quantile(q: ${aggregation}) else (tables=<-) => tables |>  mean() \r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requestsRaw\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ping-scc\")\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"userLocation\"] =~ /${userLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"btpLocation\"] =~ /${btpLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"s4hLocation\"] =~ /${s4hLocation:regex}/)\r\n  |> filter(fn: (r) => r[\"requestName\"] =~ /${request:regex}/)\r\n  |> filter(fn: (r) => r[\"connectionType\"] =~ /${connectionType:regex}/)\r\n  |> group(columns: [\"scenario\",\"userLocation\",\"connectionType\",\"btpLocation\",\"s4hLocation\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (column, tables=<-) => tables |> aggregate(), createEmpty: false)  \r\n",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}